services:
  backend:
    build: ./backend
    environment:
      - SECRET_TOKEN=${SECRET_TOKEN}
      - VITE_PROD_URL=${VITE_PROD_URL}
      - YF_URL=${YF_URL}
  frontend:
    depends_on:
      - backend
    build: ./frontend

